---
- name: Update Nginx config with backend details
  template:
    src: ../nginx/templates/epicbook.conf.j2
    dest: /etc/nginx/sites-available/epicbook
    mode: "0644"
  become: yes

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/epicbook
    dest: /etc/nginx/sites-enabled/epicbook
    state: link
  become: yes

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
  become: yes